[device_req]
device_type = "ANDROID"
sn = "c46f8a556b87c87bb1928ea6ab12ef6918b71f5c37fbd53b88e9353ea2093f1c"

code = "sdk_gphone64_arm64"
system_ver = "15_12592187"
app_id = "18071adc038afff6630"
app_version = "2.0.0"
invitee = true

[create_wallet_req]
language_code = 1

phrase = "supreme traffic broom tired skin young metal stairs own globe transfer buzz"
salt = "87654321"
wallet_name = "my wallet 5"
account_name = "my account 5"
is_default_name = true
wallet_password = "q1111111"
invite_code = "I1912683353004912640"

[create_account_req]
wallet_address = "0xDA32fc1346Fa1DF9719f701cbdd6855c901027C1"
root_password = "q1111111"
index = 1
name = "my account 5"
is_default_name = true
