[package]
name = "wallet-ecdh"
version = "0.1.0"
edition = "2024"

[dependencies]
k256 = { version = "0.13", features = ["ecdh", "ecdsa-core", "sha2"] }
rand_core = "0.6"
hex = "0.4"
# 加密相关依赖
aes-gcm = "0.10"
base64 = "0.21"
# HKDF 和哈希函数
hkdf = "0.12"

[dev-dependencies]